/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as React from "react"
import { useGLTF } from '@react-three/drei'

const CityModel = (props:any) => {
  const { nodes, materials } = useGLTF('/models/city/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Dtla_Orbit_Dtla_Orbit_u3_v1_0.geometry}
            material={materials.Dtla_Orbit_u3_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Dtla_Orbit_Dtla_Orbit_u3_v1_0_1.geometry}
            material={materials.Dtla_Orbit_u3_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Dtla_Orbit_Dtla_Orbit_u3_v1_0_2.geometry}
            material={materials.Dtla_Orbit_u3_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Dtla_Orbit_Dtla_Orbit_u3_v1_0_3.geometry}
            material={materials.Dtla_Orbit_u3_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Dtla_Orbit_Dtla_Orbit_u1_v1_0.geometry}
            material={materials.Dtla_Orbit_u1_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Dtla_Orbit_Dtla_Orbit_u1_v1_0_1.geometry}
            material={materials.Dtla_Orbit_u1_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Dtla_Orbit_Dtla_Orbit_u1_v1_0_2.geometry}
            material={materials.Dtla_Orbit_u1_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v2_0.geometry}
            material={materials.Dtla_Orbit_u2_v2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v2_0_1.geometry}
            material={materials.Dtla_Orbit_u2_v2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v2_0_2.geometry}
            material={materials.Dtla_Orbit_u2_v2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v2_0_3.geometry}
            material={materials.Dtla_Orbit_u2_v2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v1_0.geometry}
            material={materials.Dtla_Orbit_u2_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v1_0_1.geometry}
            material={materials.Dtla_Orbit_u2_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v1_0_2.geometry}
            material={materials.Dtla_Orbit_u2_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Dtla_Orbit_Dtla_Orbit_u2_v1_0_3.geometry}
            material={materials.Dtla_Orbit_u2_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Dtla_Orbit_Dtla_Orbit_u1_v2_0.geometry}
            material={materials.Dtla_Orbit_u1_v2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Dtla_Orbit_Dtla_Orbit_u1_v2_0_1.geometry}
            material={materials.Dtla_Orbit_u1_v2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Dtla_Orbit_Dtla_Orbit_u1_v2_0_2.geometry}
            material={materials.Dtla_Orbit_u1_v2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Dtla_Orbit_Dtla_Orbit_u1_v2_0_3.geometry}
            material={materials.Dtla_Orbit_u1_v2}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/city/scene.gltf')

export default CityModel
