/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: natcrot (https://sketchfab.com/natcrot)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/white-room1-26a61fba0d5d41dcbe01478de9831218
Title: White-room1
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const RoomModel = (props:any) => {
  const { nodes, materials } = useGLTF('/models/room2/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.915}>
        <lineSegments geometry={nodes.Object_2.geometry} material={materials.Material} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.ceiling}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.floor}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.light}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.walls}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.metallic_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.painting}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.window_frame}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/room2/scene.gltf')

export default RoomModel
